### ISSUE TITLE
There was an error setting up robot events.

### ISSUE THREAD

**Issue by Dementei** [Firebottle/BeamChatPlays#25] opened 2016-09-24 05:34 UTC
I had BCP working for an hour or so but then I restarted it and tried to connect again, and it gave me an "Error with robot" message. I've restarted my computer but it didn't fix, is there something I can do to fix this? Thanks.

Oh and I support the ability to click with mouse control please, off by default but can be toggled. Would make shooting games really cool to play on stream.

Edit: I made a new Game under Beam Labs and it seems to be working again, the old one must have gotten bugged somehow.

**Comment by Firebottle** [comment] 2016-09-26 17:30
Glad you got it working! Could have been caused by many different things. Let me know if you run into the issue again.

As for shooting games, you can always rebind the fire key to be a button press. Noted on the mouse control though. It's something I'll consider later on.

Closing this one for now.

**Closed by Firebottle** 2016-09-26 17:30 UTC
